# Generated by Django 3.1.7 on 2023-01-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiContextStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS_ID', models.CharField(max_length=250)),
                ('STATUS_CODE', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('ORDER_ID', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
        ),
    ]
