# Generated by Django 3.2.10 on 2022-07-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiContextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=25)),
                ('core_version', models.CharField(max_length=200)),
                ('bap_id', models.CharField(max_length=200)),
                ('bap_uri', models.CharField(max_length=200)),
                ('bpp_id', models.CharField(max_length=200)),
                ('bpp_uri', models.CharField(max_length=200)),
                ('transaction_id', models.CharField(max_length=200)),
                ('message_id', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('key', models.CharField(max_length=500)),
                ('ttl', models.CharField(max_length=500)),
            ],
        ),
    ]
