# Generated by Django 3.2.10 on 2022-07-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiContextCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATEGORY_NAME', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='apicontextmodel',
            name='timestamp',
            field=models.CharField(max_length=200),
        ),
    ]
