# Generated by Django 3.2.10 on 2022-07-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_search', '0002_auto_20220725_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicontextcategory',
            name='CATEGORY_CODE',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='apicontextcategory',
            name='CATEGORY_DURATION',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='apicontextcategory',
            name='CATEGORY_IMAGES',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='apicontextcategory',
            name='CATEGORY_LONGDESC',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='apicontextcategory',
            name='CATEGORY_RANGEDAYS',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='apicontextcategory',
            name='CATEGORY_SHORTDESC',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='apicontextcategory',
            name='CATEGORY_SYMBOL',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='apicontextcategory',
            name='CATEGORY_TIMELABLE',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='apicontextcategory',
            name='CATEGORY_TIMESTAMP',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
