# Generated by Django 3.1.7 on 2022-07-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_search', '0004_auto_20220725_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiContextProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROVIDER_NAME', models.CharField(max_length=250)),
                ('PROVIDER_CODE', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('PROVIDER_SYMBOL', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('PRODIVER_SHORTDESC', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('PROVIDER_LONGDESC', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('PROVIDER_IMAGES', models.ImageField(blank=True, default=None, null=True, upload_to='upload')),
                ('PR0VIDER_TIMELABLE', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('PROVIDER_TIMESTAMP', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('PROVIDER_DURATION', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('PROVIDER_RANGEDAYS', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='apicontextcategory',
            old_name='CATEGORY_RANGEDAYS',
            new_name='CATEGORY_RANGEENDDAYS',
        ),
        migrations.AddField(
            model_name='apicontextcategory',
            name='CATEGORY_RANGESTDAYS',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
